---
- name: "Lets go ahead and add the root user and keys"
  user:
    name: root
    shell: "/bin/bash"
    state: present

- name: "Add the Authorized Key File"
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_ecdsa.pub') }}"