---
- name: add apt key for Docker
  apt_key: url='https://download.docker.com/linux/ubuntu/gpg' state=present

- name: add apt repo for Docker
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable' state=present

- name: Update again for Docker
  apt: update_cache=yes
  changed_when: False

- name: Lets get the docker py
  pip:
    name: "{{ oob_pip_packages }}"

- name: Let's move docker-compose.yml to the root directory
  copy:
    src: docker-compose.yml
    dest: "/root/docker-compose.yml"

- name: Let's get the Docerfile over to the right Directory"
  copy: 
    src: guacamole-dockerfile
    dest: /root/guacamole/Dockerfile

- name: Lets get this guacamole thing going
  docker_compose:
    project_src: /root 
    state: present
  register: output

- name: What does docker look like
  debug:
    var: output
