"""empty message

Revision ID: 50810cd2e976
Revises: 
Create Date: 2018-08-13 12:13:23.679147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50810cd2e976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('host_status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    # ### end Alembic commands ###
