---
- name: apply a common playbook to linux servers in the CDC lab
  hosts: linux_servers
  remote_user: root
  become: yes

  roles:
  - common

- name: Let's get oobserver in order
  hosts: oobserver
  remote_user: root
  become: yes

  roles:
  - oobserver